### ISSUE TITLE
[Commands] Put Command List Here Please

### ISSUE THREAD

**Issue by Skyladd** [TKRT-Creations/SkyBlockPVP#7]
Commands Below
----------------------
**Done:**
- [x] /is - main Skyblock command
- [x] /is create - Creates a island
- [x] /is delete - deletes a island
- [x] /is get - Gets player island location
- [x] /is warp - Warp to players island
- [x] /is help - shows all commands of SkyblockPVP

**To-do:**
- [ ] /is team - shows your island team list (your island)
   - [ ] /is invite @player - adds player
   - [ ] /is allow @player - triggers for editing island
   - [ ] /is remove @player - removes a player
- [ ] /is kick @player - kicks specified player from island

- [ ] /is warp (player) - warps a player to a island
- [ ] /is warp <on/off> - turns on or off warp features on your island
- [ ] /is setwarp - sets warp spawnpoint.

**Comment by TheKillerTacos** [comment]
ok

**Comment by Skyladd** [comment]
Also do you need help with anything else other than php code? Does English translation take php? If i can help with anything let me know

**Comment by TheKillerTacos** [comment]
/is - main Skyblock command
/is create - Creates a island
/is delete - deletes a island
/is get <player> - Gets player island location
/is get tp <player> - TP you to a players island
/is help - shows all commands of SkyblockPVP

**Comment by TheKillerTacos** [comment]
Maybe on Spelling, since i actually pass that stuff,

**Comment by Skyladd** [comment]
sure ill be happy to help, i hope you dont mind that i updated the README.md

**Comment by TheKillerTacos** [comment]
Nah.

**Comment by Skyladd** [comment]
Can you add a permission like sbpvp.* to give all permissions?

**Comment by TheKillerTacos** [comment]
well, if player doesnt has the sbpvp permission, He cant run any command of SkyblockPVP

**Comment by Skyladd** [comment]
i know i mean for op sbpvp.* instead of giving a player all of the permissions one by one that one perm would allow all commands to be used.

**Comment by TheKillerTacos** [comment]
its autocratically given to player,
let me update the plugin.yml so you can see what im talking about

**Comment by Skyladd** [comment]
I see, one recommendation is it possible to change the /is get tp to /is warp @player?

**Comment by TheKillerTacos** [comment]
yea, you change that in the wiki, i do that on the plugin.yml

**Comment by Skyladd** [comment]
Sweet, should the /is warp be for normal players too? Since other players cant edit their island??

**Comment by TheKillerTacos** [comment]
they could simply TPA with essentials, but ill add the /is invite feature, with options. like
/is friends - shows your friends list (your island)
/is friends mod @player - triggers for editing island
/is friends delete @player - deletes a friend
/is friends add @player - adds player

**Comment by Skyladd** [comment]
Just a suggestion--

/is team - shows your island team list (your island)
/is allow @player - triggers for editing island
/is kick  @player - kicks specified player from island
/is invite @player - adds player

**Comment by Skyladd** [comment]
I think it would be cool to have /is warp because they could see the players island without them being online, but they couldnt edit anything. One thing though, will you make it to where they cant kill your animals but can kill monsters?

**Comment by TheKillerTacos** [comment]
yea that is posible, there are 2 ways to do it,

1. Make automatic Area protector (55x55 blocks) so only players can edit the island and kill mobs 
2. Record Mobs within that area so only players can hit them

**Comment by TheKillerTacos** [comment]
/is warp on - will set warpable their island
/is warp off - will unset warpable island
so only players who have that option will be able to get other players warp to their islands

**Comment by Skyladd** [comment]
Awesome. So glad thats possible lol. yes the /is warp on and off is a very good idea. Might want to add a /is setwarp as well

**Comment by TheKillerTacos** [comment]
ok, like "sethome" but this one will let the player set the warp point (like if they make a IslandShop they get the players where they want to spawn,) but also it will make trolls...

**Comment by Skyladd** [comment]
is it possible to allow keepinventory when on another players island?

**Comment by TheKillerTacos** [comment]
hmmm, yea, ill make a status, like the plugin checks if Player is SafeMode or not so when they warp to another island they get SafeMode, if they go back to their island, it deactivates, and if they are in SafeMode and go to Spawn/lobby it automatically deactivate safemode

**Comment by Skyladd** [comment]
yes good :) that will stop the island trolls

**Comment by TheKillerTacos** [comment]
yea, hehe. going to add all this to the TODO

**Comment by Skyladd** [comment]
good idea, are you working on the plugin right now?

**Comment by TheKillerTacos** [comment]
yea,

**Comment by TheKillerTacos** [comment]
making Main.php

**Comment by Skyladd** [comment]
i hope the php7 isnt too hard for you, all of the servers are upgrading to php7 now

**Comment by TheKillerTacos** [comment]
yea, but it wont be hard, its somehow the same, just minor changes but HIGHER performance

**Comment by Skyladd** [comment]
i know, my server runs way faster now lol.

**Comment by Skyladd** [comment]
added GNU public license

**Comment by TheKillerTacos** [comment]
Ok, going to delete some comments, its just way too long in here

**Comment by Skyladd** [comment]
Hey can you make the skyblock world be its own world as in it makes a world specifically for all the islands? As of right now it generates them in a world other than the lobby right?

**Comment by TheKillerTacos** [comment]
the Lobby is the spawn, then there will be another World, where the island will be generated.

**Comment by Skyladd** [comment]
If you made that then we wouldnt need a lobby, it would just make its own world with all the islands

**Comment by Skyladd** [comment]
also i recommend changing spa to es in the config, may be more convenient for espanol users, up to you though

**Comment by TheKillerTacos** [comment]
hmmm, what if i make a world generator that creates 100 islands and has them all in a log:
Island 1:
  owner: none
  location: x y z
and so on, and it could generate some worlds, but that would be hard, i guess that the lobby/world option will be triggerable
because like me i want this plugin as a KitPVP and skyblock implemention, so i have 1 world with everything

**Comment by TheKillerTacos** [comment]
yea i know, ill do it, but in the pm file spa is the one, and in some plugins is spa, but THIS IS OUR PLUGIN

**Comment by Skyladd** [comment]
Having one world named skyblock would be cool, the islands would be generated as needed though so if a new player does /is create it would make an island in the skyblock world XX amount of blocks away from another one--- and yeah OUR SERVER!! xD

**Comment by TheKillerTacos** [comment]
if player does /is create, it will load a random island chunks so it loads the islands and tp's the player there, and when there are unused island/empty/unclaimed islands the chunks just unload for performance, and triggerable on Config.yml

**Comment by TheKillerTacos** [comment]
Adding to TODO

**Comment by Skyladd** [comment]
Good, would it be possible to configure how large the island plots are?

**Comment by TheKillerTacos** [comment]
hmm. maybe, but for now would be the island is showed you:
![maxresdefault](https://cloud.githubusercontent.com/assets/14338036/13194688/7969f21a-d760-11e5-8537-7ea58d765248.jpg)
But ill add different islands generators at 1.0.0B as soon as posible,

**Comment by TheKillerTacos** [comment]
and here is my website: thekillertacos.tk, still in WIP, create an account, ill give ya admin, so you can also help me there. is a WordPress CMS

**Comment by Skyladd** [comment]
Nono, i mean like so your plot is 100 blocks big so you can build up to 100 blocks away from the island, but after the 100 blocks it will be protected

**Comment by Skyladd** [comment]
Okay^

**Comment by TheKillerTacos** [comment]
o yea, thats what i was going to say,

**Comment by TheKillerTacos** [comment]
but like i said for now will be 55x55, so within that area, island owner can build within it.

**Comment by Skyladd** [comment]
cool, make it configureable later on xD

**Comment by TheKillerTacos** [comment]
yea, Deleting some comments....
later ill add a chat on the website.

**Comment by Skyladd** [comment]
k, figuring out how to sign up now :P

**Comment by TheKillerTacos** [comment]
Do you have Telegram, Gitter? or we should use a IRC?

**Comment by TheKillerTacos** [comment]
hehe wait...

**Comment by Skyladd** [comment]
i have telegram

**Comment by TheKillerTacos** [comment]
ok, im @TheKillerTacos :P

**Comment by Skyladd** [comment]
Byron?

**Comment by TheKillerTacos** [comment]
yep

**Comment by Skyladd** [comment]
added

**Comment by TheKillerTacos** [comment]
ok, see ya there

**Comment by TheKillerTacos** [comment]
I'll just lock this.

**Comment by TheKillerTacos** [comment]
Closing, added this to TODO
